name: Update Reddit Subscribers

on:
  schedule:
    - cron: "0 0 * * *" # يحدث مرة يوميًا منتصف الليل UTC
  workflow_dispatch:    # يسمح لك بتشغيله يدويًا

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Reddit subscribers
        run: |
          SUBS=$(curl -s -A "Mozilla/5.0" "https://www.reddit.com/r/Daruza/about.json" | jq '.data.subscribers')
          echo "{\"subscribers\": $SUBS}" > .github/data/reddit.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .github/data/reddit.json
          git commit -m "Update Reddit subscribers"
          git push
